---
title: "Empirical IO study"
author: "Hyoungchul Kim"
execute: 
  freeze: auto
format: 
  html:
    toc: false
    number-sections: true
    code-overflow: wrap
---

This page contains an outline of the topics, contents, and works I did for Empirical IO self-study. 

**Notes**

Materials I am using: [IO syllabus by Phil Haile](https://www.dropbox.com/scl/fi/qtqqcn7kbx44a46y776ha/syll_fall24.pdf?rlkey=igszdkadeezs4qqdeicoa70v3&e=1&dl=0); [MIT IO opencourse](https://ocw.mit.edu/courses/14-271-industrial-organization-i-fall-2022/pages/syllabus/); [Train's textbook](https://eml.berkeley.edu/books/train1201.pdf); [Mixetape course on demand estimation](https://github.com/Mixtape-Sessions/Demand-Estimation); Some bits of Tirole's textbook.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/16al0i5qXkKP0wKX86-TRgB0zpJRbwZywreXhBo--wSk/edit?usp=sharing", sheet = "io")
```

::: column-screen-right
```{r, echo = FALSE}
d |>
  mutate(
    date = as.Date(date),
    week = ifelse(is.na(week), "", week)
  ) |>
  gt() |>
  text_transform(cells_body(columns = c(link)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("book", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('book')}</a>")
      )
    }
  ) |>
#   text_transform(cells_body(columns = c(slides)),
#     fn = function(x) {
#       ifelse(is.na(x), fontawesome::fa("laptop", fill_opacity = 0.1),
#         glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>")
#       )
#     }
#   ) |>
  # text_transform(cells_body(columns = c(ae)),
  #   fn = function(x) {
  #     ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
  #       glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
  #     )
  #   }
  # ) |>
  # text_transform(cells_body(columns = c(ae_sa)),
  #   fn = function(x) {
  #     ifelse(is.na(x), fontawesome::fa("key", fill_opacity = 0.1),
  #       glue::glue("<a href = {x}>{fontawesome::fa('key')}</a>")
  #     )
  #   }
  # ) |>
  text_transform(cells_body(columns = c(material)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("keyboard", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('keyboard')}</a>")
      )
    }
  ) |>
#   text_transform(cells_body(columns = c(hw_sol)),
#     fn = function(x) {
#       ifelse(is.na(x), fontawesome::fa("key", fill_opacity = 0.1),
#         glue::glue("<a href = {x}>{fontawesome::fa('key')}</a>")
#       )
#     }
#   ) |>
  # text_transform(cells_body(columns = c(lab)),
  #   fn = function(x) {
  #     ifelse(is.na(x), fontawesome::fa("users-rectangle", fill_opacity = 0.1),
  #       glue::glue("<a href = {x}>{fontawesome::fa('users-rectangle')}</a>")
  #     )
  #   }
  # ) |>
  # text_transform(cells_body(columns = c(lab_sa)),
  #   fn = function(x) {
  #     ifelse(is.na(x), fontawesome::fa("key", fill_opacity = 0.1),
  #       glue::glue("<a href = {x}>{fontawesome::fa('key')}</a>")
  #     )
  #   }
  # ) |>
#   text_transform(cells_body(columns = c(exam)),
#     fn = function(x) {
#       ifelse(is.na(x), fontawesome::fa("file-circle-check", fill_opacity = 0.1),
#         glue::glue("<a href = {x}>{fontawesome::fa('file-circle-check')}</a>")
#       )
#     }
#   ) |>
  # text_transform(cells_body(columns = c(project)),
  #   fn = function(x) {
  #     ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
  #       glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
  #     )
  #   }
  # ) |>
  fmt_date(date, date_style = 30) |>
  sub_missing(columns = c(date, what, topic, notes), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(week, dow, link, material)
    ) |>
  cols_align(
    align = "left", 
    columns = c(date, what, topic, notes)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, link, material)
    )
  )
```
:::