---
title: "Probability theory"
subtitle: "My log for studying probability theory"
execute:
  freeze: false
---

This pages contains log for my self-study on probability theory.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/16al0i5qXkKP0wKX86-TRgB0zpJRbwZywreXhBo--wSk/edit?usp=sharing", sheet = "probs")
```

::: column-screen-right
```{r, echo = FALSE}
d |>
  mutate(
    date = as.Date(date),
    week = ifelse(is.na(week), "", week)
  ) |>
  gt() |>
  text_transform(cells_body(columns = c(hw)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("keyboard", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('keyboard')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(hw_sol)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("key", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('key')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(exam)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("file-circle-check", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('file-circle-check')}</a>")
      )
    }
  ) |>
  fmt_date(date, date_style = 30) |>
  sub_missing(columns = c(date, topic, notes), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(week, hw, hw_sol, exam)
    ) |>
  cols_align(
    align = "left", 
    columns = c(date, topic, notes)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, hw_sol, exam)
    )
  )
```
:::